Repository conveyordata/data-product-portal, pull requests merged in 2024-07, with the labels that each got.

#30 Add John Doe as default unauthenticated user
  backend/app/core/auth/auth.py
Labels: enhancement

#31 Implement clearer error messages when certain features are disabled
  backend/app/core/conveyor/notebook_builder.py
  backend/app/data_products/service.py
  backend/sample_data.sql
Labels: enhancement

#36 Feature/build docker on main
  .github/workflows/docker-build-main.yml
Labels: enhancement

#35 Fix/conveyor auth without OIDC
  VERSION
  backend/VERSION
  backend/app/core/auth/oidc.py
  backend/app/core/conveyor/notebook_builder.py
  helm/Chart.yaml
  helm/values.yaml
Labels: bug, python

#45 Add infrastructure lambda support
  backend/.test.env
  backend/app/core/aws/boto3_clients.py
  backend/app/core/aws/refresh_infrastructure_lambda.py
  backend/app/data_product_memberships/service.py
  backend/app/data_products/service.py
  backend/app/data_products_datasets/service.py
  backend/app/datasets/service.py
  backend/app/local_startup.py
  backend/app/settings.py
  helm/templates/configmap_backend.yaml
  helm/values.yaml
Labels: python

#48 Nginx Configuration with Additional Proxy Headers for Swagger
  compose.yaml
  nginx/nginx.conf
Labels: enhancement

#58 Add defaults for missing env vars
  compose.yaml
Labels: bug

#59 Access api docs through /api/docs
  backend/app/main.py
Labels: documentation, enhancement, python
