Repository conveyordata/data-product-portal, pull requests merged in 2025-05, with the labels that each got.

#1055 fix migration
  backend/app/database/alembic/versions/2025_04_16_1658-6fd335d0dcfe_migrate_rbac.py
Labels: bug

#1069 Added CASCADE delete to fix delete bug on main
  backend/app/data_products/router.py
  backend/app/database/alembic/versions/2025_05_06_1512-7727032896e7_add_on_delete_cascade_to_role_.py
  backend/app/datasets/router.py
  backend/tests/app/role_assignments/data_product/test_router.py
  backend/tests/app/role_assignments/dataset/test_router.py
Labels: bug

#1090 Pin checkout action to hash
  .github/workflows/alembic-workflow.yml
Labels: dependencies, github_actions

#1116 Authorizer is now enabled. This breaks most unit tests
  backend/app/authorization/service.py
  backend/tests/app/authorization/test_router.py
  backend/tests/app/authorization/test_service.py
  backend/tests/app/core/authz/test_authorization.py
  backend/tests/app/data_outputs/test_router.py
  backend/tests/app/data_outputs_datasets/test_router.py
  backend/tests/app/data_product_memberships/test_router.py
  backend/tests/app/data_products/test_router.py
  backend/tests/app/data_products_datasets/test_router.py
  backend/tests/app/datasets/test_router.py
  backend/tests/app/environments/test_router.py
  backend/tests/app/role_assignments/data_product/test_auth.py
  backend/tests/app/role_assignments/data_product/test_router.py
  backend/tests/app/role_assignments/dataset/test_auth.py
  backend/tests/app/role_assignments/dataset/test_router.py
  backend/tests/app/role_assignments/global_/test_auth.py
  backend/tests/app/roles/test_router.py
  backend/tests/conftest.py
  backend/tests/factories/role.py
  backend/tests/factories/role_assignment_data_product.py
  backend/tests/factories/role_assignment_dataset.py
  backend/tests/factories/role_assignment_global.py
Labels: bug

#1160 Bug in useToken
  frontend/src/components/explorer/explorer.tsx
Labels: bug, javascript

#1159 Fix issues with latest Helm improvements
  helm/templates/configmap_backend.yaml
  helm/templates/configmap_frontend.yaml
  helm/templates/deployment_backend.yaml
  helm/templates/secret_backend.yaml
Labels: bug
