Repository conveyordata/data-product-portal, pull requests merged in 2025-04, with the labels that each got.

#984 Configmap with int value breaks the configmap
  helm/values.yaml
Labels: bug

#985 Do not recreate enum on new migration
  backend/app/database/alembic/versions/2025_03_31_1609-48c52a42d7a2_add_global_role_assignments.py
Labels: bug

#999 Fix deadlocking issue when reinitializing Casbin
  backend/app/authorization/service.py
Labels: bug

#1025 Feature/search explorer
  backend/app/graph/router.py
  backend/app/graph/service.py
  backend/app/shared/router.py
  backend/sample_data.sql
  backend/tests/app/graph/__init__.py
  backend/tests/app/graph/test_router.py
  frontend/src/api/api-urls.ts
  frontend/src/components/explorer/explorer.module.scss
  frontend/src/components/explorer/explorer.tsx
  frontend/src/components/explorer/sidebar.module.scss
  frontend/src/components/explorer/sidebar.tsx
  frontend/src/components/layout/navbar/breadcrumbs/breadcrumbs.component.tsx
  frontend/src/components/layout/sidebar/sidebar.component.tsx
  frontend/src/hooks/use-node-editor.tsx
  frontend/src/pages/explorer/explorer.page.module.scss
  frontend/src/pages/explorer/explorer.page.tsx
  frontend/src/routes.tsx
  frontend/src/store/features/data-products/data-products-api-slice.ts
  frontend/src/types/navigation.ts
Labels: enhancement, javascript, python

#1039 Fix secuirty issue with h11
  backend/poetry.lock
  backend/pyproject.toml
Labels: dependencies
