Repository conveyordata/data-product-portal, pull requests merged in 2025-06, with the labels that each got.

#1188 Add namespace to the 3 detailed pages
  frontend/src/pages/data-output/components/data-output-description/data-output-description.tsx
  frontend/src/pages/data-output/data-output.page.tsx
  frontend/src/pages/data-product/components/data-product-description/data-product-description.tsx
  frontend/src/pages/data-product/data-product.page.tsx
  frontend/src/pages/dataset/components/dataset-description/dataset-description.tsx
  frontend/src/pages/dataset/dataset.page.tsx
Labels: javascript

#1189 implement snowflake urls
  backend/app/data_products/router.py
  backend/app/data_products/service.py
  backend/sample_data.sql
  backend/tests/app/data_products/test_router.py
  frontend/src/api/api-urls.ts
  frontend/src/pages/data-product/components/data-product-actions/data-product-actions.component.tsx
  frontend/src/store/features/data-products/data-products-api-slice.ts
  frontend/src/types/data-product/data-product-snowflake-url.contract.ts
  frontend/src/types/data-product/index.ts
  frontend/src/utils/data-platforms.ts
Labels: enhancement, javascript, python

#1195 Show first and last name of users in select list at creation time
  frontend/src/components/data-products/data-product-form/data-product-form.component.tsx
  frontend/src/components/datasets/dataset-form/dataset-form.component.tsx
Labels: enhancement, javascript

#1070 Visualize domains in the Full Explorer
  backend/app/graph/node.py
  backend/app/graph/router.py
  backend/app/graph/service.py
  backend/tests/app/data_outputs/test_router.py
  backend/tests/app/data_products/test_router.py
  backend/tests/app/datasets/test_router.py
  backend/tests/app/graph/test_router.py
  frontend/src/components/charts/custom-nodes/base-node/base-node.tsx
  frontend/src/components/charts/custom-nodes/data-product-node/data-product-node.tsx
  frontend/src/components/charts/custom-nodes/dataoutput-node/dataoutput-node.tsx
  frontend/src/components/charts/custom-nodes/dataset-node/dataset-node.tsx
  frontend/src/components/charts/custom-nodes/domain-node/domain-node.tsx
  frontend/src/components/charts/node-editor/node-types.ts
  frontend/src/components/explorer/common.tsx
  frontend/src/components/explorer/explorer.tsx
  frontend/src/components/explorer/full-explorer.tsx
  frontend/src/components/explorer/node-context.tsx
  frontend/src/components/explorer/sidebar.module.scss
  frontend/src/components/explorer/sidebar.tsx
  frontend/src/components/explorer/utils.tsx
  frontend/src/pages/explorer/explorer.page.tsx
  frontend/src/store/features/api/tag-types.ts
  frontend/src/store/features/data-products/data-products-api-slice.ts
  frontend/src/store/features/graph/graph-api-slice.ts
  frontend/src/types/graph/graph-contract.ts
Labels: enhancement

#1277 fix regression in translation
  frontend/src/components/data-outputs/data-output-subtitle/data-output-subtitle.component.tsx
Labels: bug

#1283 Bug because get ignores options
  backend/app/data_products/service.py
  backend/tests/app/data_outputs_datasets/test_router.py
  backend/tests/app/data_products_datasets/test_router.py
Labels: bug
